import CivicHeader from "@/components/CivicHeader";
import StatusPill from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { Bell, CheckCircle2, ClipboardList, Leaf, MapPin, PenLine, ShieldCheck, Trophy, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

export default function CitizenProfile() {
  const { user } = useAuth();
  const profileQuery = trpc.profile.mine.useQuery();
  const profile = profileQuery.data;
  const { data: items = [] } = trpc.civicItems.mine.useQuery();
  const { data: notices = [] } = trpc.notifications.mine.useQuery();
  const { data: consents = [] } = trpc.profile.consent.useQuery();
  const utils = trpc.useUtils();
  const save = trpc.profile.save.useMutation({ onSuccess: () => profileQuery.refetch() });
  const acceptConsent = trpc.profile.acceptPlatform.useMutation({ onSuccess: () => utils.profile.consent.invalidate() });
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.mine.invalidate() });
  const [locality, setLocality] = useState(""); const [ward, setWard] = useState(""); const [district, setDistrict] = useState(""); const [publicActivity, setPublicActivity] = useState(false);
  useEffect(() => { if (profile) { setLocality(profile.locality ?? ""); setWard(profile.ward ?? ""); setDistrict(profile.district ?? ""); } }, [profile]);
  const resolved = useMemo(() => items.filter(item => item.status === "resolved" || item.status === "closed").length, [items]);
  const inProgress = useMemo(() => items.filter(item => item.status === "in_progress" || item.status === "assigned").length, [items]);
  const onSave = (event: FormEvent) => { event.preventDefault(); save.mutate({ locality: locality || null, ward: ward || null, district: district || null }); };
  const displayName = user?.name || "Citizen";
  const metrics = [[ClipboardList, items.length, "Reports", "Submitted", "#0d5ebc"], [CheckCircle2, inProgress, "In progress", "Issues", "#0b9671"], [Trophy, resolved, "Resolved", "Issues", "#f19a22"], [Leaf, 0, "Green", "Credits", "#7347cc"]] as const;
  return <div className="min-h-screen bg-[#fbfbfc]"><CivicHeader /><main className="mx-auto max-w-xl px-4 pb-28 pt-6">
    <section><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="text-2xl font-black tracking-[-.04em] text-[#151a24]">{displayName}</p><p className="mt-2 flex items-center gap-1.5 text-sm text-[#556170]"><MapPin className="h-4 w-4" />{locality || "Set your locality"}</p><p className="mt-1 text-sm text-[#6c7786]">Active civic contributor</p></div><Link href="#preferences" className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-[#124e9d] px-3 py-2 text-xs font-black text-[#064ba9]"><PenLine className="h-4 w-4" />Edit profile</Link></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-[#eaf8f1] px-3 py-1.5 text-xs font-black text-[#13805c]">Community contributor</span><span className="rounded-full bg-[#edf5ff] px-3 py-1.5 text-xs font-black text-[#0757b8]">Privacy protected</span></div></section>
    <section className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{metrics.map(([Icon, value, title, subtitle, color]) => <div key={title} className="rounded-2xl border border-[#e3e7ec] bg-white p-3"><Icon className="h-6 w-6" style={{ color }} /><p className="mt-4 text-2xl font-black text-[#131923]">{value}</p><p className="mt-1 text-xs font-black text-[#293647]">{title}</p><p className="text-[11px] text-[#748092]">{subtitle}</p></div>)}</section>
    <section className="mt-5 rounded-2xl bg-[#eef9f4] p-5"><div className="flex items-center gap-2"><Leaf className="h-5 w-5 text-[#0c9169]" /><h2 className="text-lg font-black text-[#17372f]">Your Civic Impact</h2></div><div className="mt-5 grid grid-cols-3 divide-x divide-[#cce9de] text-center"><div><p className="text-xl font-black text-[#0c7358]">{items.length}</p><p className="mt-1 text-xs text-[#52746b]">Records raised</p></div><div><p className="text-xl font-black text-[#0c7358]">{resolved}</p><p className="mt-1 text-xs text-[#52746b]">Resolved</p></div><div><p className="text-xl font-black text-[#0c7358]">{inProgress}</p><p className="mt-1 text-xs text-[#52746b]">In progress</p></div></div><p className="mt-4 text-center text-xs text-[#52746b]">Impact reflects only your real civic records in this environment.</p></section>
    <section id="preferences" className="mt-6 rounded-2xl border border-[#e3e7ec] bg-white p-5"><h2 className="text-lg font-black text-[#1a2533]">Locality preferences</h2><form onSubmit={onSave} className="mt-4 space-y-3"><label className="block text-xs font-black text-[#59697b]">Locality<input value={locality} onChange={event => setLocality(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dce2e9] px-3 text-sm outline-none focus:border-[#0d5ebc]" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-xs font-black text-[#59697b]">Ward or block<input value={ward} onChange={event => setWard(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dce2e9] px-3 text-sm outline-none focus:border-[#0d5ebc]" /></label><label className="block text-xs font-black text-[#59697b]">District<input value={district} onChange={event => setDistrict(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#dce2e9] px-3 text-sm outline-none focus:border-[#0d5ebc]" /></label></div><Button type="submit" disabled={save.isPending} variant="outline" className="w-full border-[#9bc2e7] font-black text-[#0757b8]">{save.isPending ? "Saving…" : "Save preferences"}</Button></form></section>
    <section className="mt-6 rounded-2xl border border-[#cfe7e1] bg-[#f2fbf9] p-5"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#0b8a70]" /><div><h2 className="font-black text-[#1b3c39]">Your privacy choice</h2><p className="mt-1 text-xs leading-5 text-[#557975]">Jananiti does not collect Aadhaar or biometrics. You choose whether reports can appear as privacy-safe public activity.</p></div></div><label className="mt-4 flex gap-2 text-xs font-bold text-[#466d69]"><input type="checkbox" checked={publicActivity} onChange={event => setPublicActivity(event.target.checked)} className="accent-[#0d9388]" />Allow privacy-safe public activity for my reports.</label><Button onClick={() => acceptConsent.mutate({ publicActivity })} disabled={acceptConsent.isPending} variant="outline" className="mt-4 w-full border-[#9bd5ce] bg-white text-xs font-black text-[#087b72]">{consents.length ? "Update consent" : "Save consent"}</Button></section>
    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#151a24]">Recent Activity</h2><Link href="/notifications" className="text-sm font-black text-[#064bac]">View all</Link></div>{items.length ? <div className="mt-4 space-y-3">{items.slice(0, 4).map(item => <Link key={item.publicId} href={`/track?ref=${item.publicId}`} className="flex items-center gap-3 rounded-2xl border border-[#e3e7ec] bg-white p-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#eef5ff]"><ClipboardList className="h-5 w-5 text-[#0d5ebc]" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#1d2938]">{item.title}</p><p className="mt-1 truncate text-xs text-[#6c7786]">{item.locationLabel}</p></div><StatusPill status={item.status} /></Link>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-[#d9e1e9] bg-white p-6 text-center"><ClipboardList className="mx-auto h-6 w-6 text-[#0d5ebc]" /><p className="mt-2 text-sm font-black text-[#26394d]">No personal activity yet.</p><Link href="/report" className="mt-2 inline-block text-sm font-black text-[#064bac]">Report an issue</Link></div>}</section>
    <section className="mt-7"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-black text-[#151a24]"><Bell className="h-5 w-5 text-[#0d9388]" />Updates for you</h2><Link href="/notifications" className="text-sm font-black text-[#064bac]">View all</Link></div>{notices.length ? <div className="mt-4 space-y-3">{notices.slice(0, 3).map(notice => <button key={notice.id} onClick={() => !notice.readAt && markRead.mutate({ id: notice.id })} className="w-full rounded-2xl border border-[#e3e7ec] bg-white p-4 text-left"><p className="font-black text-[#26394d]">{notice.title}</p><p className="mt-1 text-sm text-[#687789]">{notice.message}</p></button>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-[#d9e1e9] bg-white p-6 text-center"><p className="text-sm font-black text-[#26394d]">No notifications yet.</p><p className="mt-1 text-xs text-[#758497]">Receipts, authority updates, and community prompts appear here.</p></div>}</section>
  </main></div>;
}
