import CivicLifecycleTimeline from "@/components/CivicLifecycleTimeline";
import CivicMap from "@/components/CivicMap";
import { ArrowLeft, Bell, CheckCircle2, MapPin, Search, Settings2, UserRound } from "lucide-react";
import { useMemo, useState } from "react";

export type CivicWorkspaceRecord = {
  id: string;
  category: string;
  title: string;
  description: string;
  locality: string;
  status: string;
  isSyntheticTestRecord?: true;
};

type CivicRecord = CivicWorkspaceRecord;

function EmptyState({ title, detail }: { title: string; detail: string }) {
  return <div className="rounded-2xl border border-dashed border-[#cdddea] bg-[#f8fbff] p-6 text-center"><p className="font-bold text-[#24384a]">{title}</p><p className="mt-2 text-sm leading-6 text-[#627283]">{detail}</p></div>;
}

export function CivicExploreScreen({ records, onOpen, onNotice }: { records: CivicRecord[]; onOpen: (record: CivicRecord) => void; onNotice: (message: string) => void }) {
  const [query, setQuery] = useState("");
  const matchingRecords = useMemo(() => records.filter((record) => `${record.title} ${record.description} ${record.locality} ${record.category}`.toLocaleLowerCase().includes(query.toLocaleLowerCase().trim())), [records, query]);
  return <section className="civic-card civic-route-enter mt-4 rounded-[24px] border border-[#e1e6eb] bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#0064e0]">Discover</p><h2 className="mt-1 text-2xl font-bold tracking-[-.04em]">Explore your civic space</h2><p className="mt-1 text-sm leading-6 text-[#5d6c7b]">Search the records available to your account and open their real timeline.</p></div><button onClick={() => onNotice("Locality filters will use the stored profile locality after a coordinator-safe profile setting is enabled.")} className="inline-flex min-h-10 items-center gap-2 rounded-full border border-[#dfe5eb] px-3 text-xs font-bold text-[#40505f] hover:bg-[#f5f8fb]"><Settings2 className="h-4 w-4" />Filters</button></div><label className="mt-5 flex h-11 items-center gap-2 rounded-xl border border-[#dfe5eb] px-3 text-sm text-[#718191]"><Search className="h-4 w-4" /><input value={query} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Search records, locality, or category" onChange={(event) => setQuery(event.target.value)} /></label><CivicMap records={matchingRecords} onOpen={(record) => onOpen(record as CivicRecord)} onNotice={onNotice} /><div className="mt-4 grid gap-3 md:grid-cols-2">{matchingRecords.length === 0 ? <div className="md:col-span-2"><EmptyState title={records.length ? "No records match that search" : "No records available to explore"} detail={records.length ? "Try a locality, category, or different search phrase." : "Create a public report or sign in to a configured Firebase environment."} /></div> : matchingRecords.map((record) => <button key={record.id} onClick={() => onOpen(record)} className="civic-card rounded-2xl border border-[#e1e6eb] p-4 text-left transition hover:border-[#92c4f5] hover:shadow-sm"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-[#eaf4ff] px-2 py-1 text-[10px] font-bold text-[#0064e0]">{record.category}</span><span className="text-[10px] font-bold text-[#718191]">{record.isSyntheticTestRecord ? "Test only" : record.status}</span></div><h3 className="mt-3 font-bold text-[#0a1317]">{record.title}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-[#5d6c7b]">{record.description}</p><p className="mt-3 flex items-center gap-1 text-xs font-bold text-[#40505f]"><MapPin className="h-3.5 w-3.5 text-[#0064e0]" />{record.locality}</p></button>)}</div></section>;
}

export function CivicActivityScreen({ notice, onOpen, records }: { notice: string; onOpen: (record: CivicRecord) => void; records: CivicRecord[] }) {
  return <section className="mt-4 rounded-[24px] border border-[#e1e6eb] bg-white p-4 shadow-sm sm:p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#0064e0]">Activity</p><h2 className="mt-1 text-2xl font-bold tracking-[-.04em]">Your updates</h2><p className="mt-1 text-sm leading-6 text-[#5d6c7b]">Session notices and updates connected to records you can access.</p><div className="mt-5 grid gap-3">{notice ? <article className="rounded-2xl border border-[#cfe8d5] bg-[#f1fbf4] p-4"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#31a24c]" /><p className="text-sm leading-6 text-[#176838]">{notice}</p></div></article> : <EmptyState title="No new updates in this session" detail="When you create, verify, react to, or comment on a real public record, the latest action will appear here." />}{records.filter((record) => !record.isSyntheticTestRecord).slice(0, 3).map((record) => <button key={record.id} onClick={() => onOpen(record)} className="flex items-center justify-between gap-3 rounded-2xl border border-[#e1e6eb] p-4 text-left hover:border-[#92c4f5]"><span><strong className="block text-sm text-[#0a1317]">{record.title}</strong><span className="mt-1 block text-xs text-[#627283]">Status: {record.status.replaceAll("_", " ")}</span></span><span className="text-xs font-bold text-[#0064e0]">View</span></button>)}</div></section>;
}

export function CivicProfileScreen({ userName, records, onNotice }: { userName: string; records: CivicRecord[]; onNotice: (message: string) => void }) {
  const ownRecords = records.filter((record) => !record.isSyntheticTestRecord);
  return <section className="mt-4 rounded-[24px] border border-[#e1e6eb] bg-white p-4 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#eaf4ff] text-[#0064e0]"><UserRound className="h-7 w-7" /></span><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#0064e0]">Citizen profile</p><h2 className="truncate text-2xl font-bold tracking-[-.04em]">{userName}</h2><p className="text-sm text-[#5d6c7b]">Your data comes from your Firebase account and accessible civic records.</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f7fbff] p-4"><p className="text-2xl font-bold text-[#0064e0]">{ownRecords.length}</p><p className="mt-1 text-xs font-bold text-[#40505f]">Reports visible to you</p></div><div className="rounded-2xl bg-[#f7fbff] p-4"><p className="text-2xl font-bold text-[#0064e0]">—</p><p className="mt-1 text-xs font-bold text-[#40505f]">Verified issues</p></div><div className="hidden rounded-2xl bg-[#f7fbff] p-4 sm:block"><p className="text-2xl font-bold text-[#0064e0]">—</p><p className="mt-1 text-xs font-bold text-[#40505f]">Civic impact</p></div></div><button onClick={() => onNotice("Profile editing will be enabled after the protected Firebase profile setting is published.")} className="mt-5 min-h-11 rounded-xl border border-[#0064e0] px-4 text-sm font-bold text-[#0064e0] hover:bg-[#eaf4ff]">Profile settings</button></section>;
}

export function CivicDetailScreen({ record, onBack, onDiscuss }: { record: CivicRecord; onBack: () => void; onDiscuss: () => void }) {
  return <section className="mt-4 rounded-[24px] border border-[#e1e6eb] bg-white p-4 shadow-sm sm:p-6"><button onClick={onBack} className="inline-flex min-h-10 items-center gap-2 rounded-full text-sm font-bold text-[#0064e0] hover:bg-[#eaf4ff] px-2"><ArrowLeft className="h-4 w-4" />Back to feed</button><span className="mt-4 inline-flex rounded-full bg-[#eaf4ff] px-2.5 py-1 text-[11px] font-bold text-[#0064e0]">{record.category}</span><h2 className="mt-3 text-2xl font-bold tracking-[-.04em] text-[#0a1317]">{record.title}</h2><p className="mt-2 flex items-center gap-1 text-sm font-bold text-[#40505f]"><MapPin className="h-4 w-4 text-[#0064e0]" />{record.locality}</p><p className="mt-4 text-sm leading-7 text-[#526171]">{record.description}</p><CivicLifecycleTimeline status={record.status} />{record.isSyntheticTestRecord ? <p className="mt-4 rounded-xl border border-[#f1d796] bg-[#fff9e6] p-3 text-xs leading-5 text-[#795b11]">This is a synthetic test record. It cannot be treated as a public civic claim.</p> : <button onClick={onDiscuss} className="mt-4 min-h-11 rounded-xl bg-[#0064e0] px-4 text-sm font-bold text-white hover:bg-[#0457cb]">Discuss in feed</button>}</section>;
}
